name: Mirror repositories

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:rafugafu/PyNotes.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH_KEY }}

      - name: Setup SourceForge SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SOURCEFORGE_SSH_KEY }}" > ~/.ssh/sourceforge_key

          chmod 600 ~/.ssh/sourceforge_key

          cat > ~/.ssh/config <<EOF
          Host git.code.sf.net
            HostName git.code.sf.net
            User git
            IdentityFile ~/.ssh/sourceforge_key
            IdentitiesOnly yes
          EOF

          ssh-keyscan git.code.sf.net >> ~/.ssh/known_hosts

      - name: Test SourceForge Authentication
        run: |
          ssh -i ~/.ssh/sourceforge_key -o IdentitiesOnly=yes -Tv git@git.code.sf.net || true

      - name: Mirror to SourceForge
        run: |
          git remote add sourceforge ssh://rafugafu@git.code.sf.net/p/pynotespython/code
          git push --mirror sourceforge